title: Sakshi Rathi
email: rathi036@umn.edu
description: "Portfolio and Blog of Sakshi Rathi"
baseurl: ""
url: "https://SakshiRa.github.io"

theme: lanyon

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

author:
  name: Sakshi Rathi
  email: rathi036@umn.edu

social:
  github: SakshiRa
  linkedin: https://www.linkedin.com/in/sakshi-rathiuofm/

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

paginate: 5
paginate_path: "/page:num/"
